### PR TITLE
More text details

### PR DESCRIPTION
**Pull request by phase**
I have no idea why @smealum loves putting spaces in front of punctuation marks, but they should be fixed now !

:smile:

### CODE REVIEW

**Comment by phase** [comment]
I also want to work on making it more that a black screen with text, maybe add some graphics or something.

**Comment by phase** [comment]
That last commit will remove all the files from `build/` and `3ds/`, so `make clean all` is more useful.

**Comment by meladroit** [comment]
Spaces in front of punctuation marks is a French thing. I happen to think it's quite charming, but oh well.

**Comment by meladroit** [comment]
Incidentally, we're at the point where I think you may want to create a standalone repo out of mine, so that you're not so reliant on my continuing to maintain this one (hint: I may stop doing so quite soon)—you'd have your commits show up on your GitHub page, too!

**Pull request merged**
