### PR TITLE
Add 10.x firmware version & Remove Ironhax files

### PR DESCRIPTION
**Pull request by phase**
Should be right!

### CODE REVIEW

**Comment by phase** [comment]
hold on...
don't push this yet :smile:

**Comment by phase** [comment]
This commit removes all the files used in Ironhax. Should be good to go!

**Comment by meladroit** [comment]
Thanks for the cleanup! I think I'm going to revert at least one typo correction, though. It works when you take screen width into account.

**Comment by phase** [comment]
@meladroit Any other frontend things you need done? :smile:

**Comment by meladroit** [comment]
I think we'll be fine unless/until new payloads start emerging for whatever reason. Thanks again!

**Comment by phase** [comment]
I'd also recommend turning issues on in the repo settings, so people can report any issues they find!

**Comment by meladroit** [comment]
Done! Didn't realise it was missing—must be because it's a fork.

**Comment by phase** [comment]
Github automatically turns them off for forks (thanks, github...). What about making it a standalone repo? You can rename this one, then use [the GitHub Importer](https://import.github.com/new) and choose this repo and name it `oot3dhax_installer`.

**Comment by meladroit** [comment]
I briefly considered it, but I dunno. With issues back on, and with very little in the way of substantial differences from sploit_installer, I don't see a compelling reason to make this standalone.

**Comment by phase** [comment]
It won't show up in your GitHub contributions graph if you don't push the commits to the original repo!:smile: 

GitHub doesn't really treat forks well, **at all**, and making it an official repo would make it seem more, _official_. I usually make it a new repo when I've changed so much that it's a completely different project, especially when you've done **25 out of the 26 commits to the repo**.

**Pull request merged**
