### PR TITLE
Remove Ironhax version selection

### PR DESCRIPTION
**Pull request by phase**
No new build because I'm having trouble building any 3DS project on my system. This should remove the Ironhax selection.

### CODE REVIEW

**Comment by meladroit** [comment]
Good idea. I wanted to leave it in as a joke (and as a way of acknowledging how blatantly this clones the ironhax installer) but it seems to cause some confusion for people asking for support. Build will hopefully be up in a little bit.

**Comment by phase** [comment]
@meladroit Might want to wait a sec on that build as I'm changing up some more stuff :smile:

**Comment by meladroit** [comment]
Oh, if you're working on some stuff, could you perhaps add 10.0 in the FW version selection? It should work with the exact same payloads as 9.9 anyway, for the most part.

**Comment by phase** [comment]
I believe I just have to do `const char* firmware_labels[][10] = {{"OLD 3DS", "NEW 3DS"}, {"9", "10"}, {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}, {"0"}, {"USA", "EUR", "JPN"}};`, but are there any tables anywhere?

**Comment by meladroit** [comment]
No, it just passes the selected labels through to getMenuVersion (also in firmware.h), I think. (Also, isn't there a variable somewhere specifying the number of labels in each field?)

**Comment by phase** [comment]
Is there any special return value for v10, or does it work with `19456` (which it will set it to by default on v10 systems)?

**Comment by meladroit** [comment]
That sounds mostly right. You'll have to account for the special case of FW 10.x USA region (20480_usa, same as 9.x USA).

**Comment by phase** [comment]
Is FW 10.x the same as FW 9.x?

**Comment by meladroit** [comment]
No, but the same payload works on both (as well as 8.x for non-USA, I think).

**Comment by phase** [comment]
_Confirming this (and everything else) works on `OLD 3DS 9.9.0 USA`!_

**Pull request merged**
